name: scottcramer
favicon: null
layout_spectrum: 0.8239418589510024
typography_spectrum: 0.8437095421832055
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.23700359323993325
  lightness: 0.9273362383246422
  saturation: 0.028067946434020996
  rhythmicContrast: 0.015638892771676183
purpose: []
